#!/usr/bin/env bash
# Bring up a local dev environment: kind cluster + stub CRDs + our CRDs.
# Run once; subsequent runs are idempotent.
set -euo pipefail

KIND_CLUSTER=fleet-dev

for cmd in kind kubectl docker go; do
    command -v "$cmd" &>/dev/null || { echo "ERROR: $cmd not found in PATH"; exit 1; }
done

# kind cluster
if kind get clusters 2>/dev/null | grep -q "^${KIND_CLUSTER}$"; then
    echo "kind cluster '${KIND_CLUSTER}' already exists"
else
    echo "Creating kind cluster '${KIND_CLUSTER}'..."
    kind create cluster --name "$KIND_CLUSTER"
fi

# CRDs: ours (generated by make generate) + stubs for MCE-provided types
echo "Applying CRDs..."
if [ -d config/crd ]; then
    kubectl apply -f config/crd/ 2>/dev/null || true
fi
kubectl apply -f config/test/crds/

echo ""
echo "=== Dev environment ready ==="
echo ""
echo "Next steps:"
echo ""
echo "  1. Start Postgres + seed data:"
echo "       docker compose up -d"
echo "       # Wait for healthy: docker compose ps"
echo ""
echo "  2. Start mock collector servers (each in its own terminal):"
echo "       go run ./hack/mock/ome          # OME REST  →  :8081"
echo "       go run ./hack/mock/intersight   # Intersight PVA  →  :8082"
echo "       go run ./hack/mock/ucsm         # UCSM XML  →  :8083"
echo ""
echo "  3. Apply test resources:"
echo "       kubectl apply -f config/test/samples/"
echo ""
echo "  4. Simulate discovered facts (projector won't act until identity is written):"
echo "       kubectl patch inventoryrecord SRV001 --type=merge --subresource=status \\"
echo "         -p '{\"status\":{\"identity\":{\"serviceTag\":\"SRV001\",\"vendor\":\"Dell\",\"model\":\"PowerEdge R750\"}}}'"
echo "       kubectl patch inventoryrecord SRV002 --type=merge --subresource=status \\"
echo "         -p '{\"status\":{\"identity\":{\"serviceTag\":\"SRV002\",\"vendor\":\"Dell\",\"model\":\"PowerEdge R750\"}}}'"
echo ""
echo "  5. Run the manager:"
echo "       go run ./cmd/manager \\"
echo "         --mce=dev \\"
echo "         --agent-namespace=default \\"
echo "         --postgres-url='postgres://postgres:fleet@localhost/fleet'"
echo ""
echo "  6. Verify store state:"
echo "       psql -h localhost -U postgres -d fleet -c 'SELECT * FROM host_capacity;'"
echo "       psql -h localhost -U postgres -d fleet -c 'SELECT * FROM region_headroom;'"
echo ""
echo "  7. Simulate binding (triggers SetAllocation within 30s):"
echo "       kubectl apply -f config/test/samples/bind-srv001.yaml"
echo "       # Then:"
echo "       psql -h localhost -U postgres -d fleet -c 'SELECT * FROM host_allocation;'"
